### ISSUE TITLE
Build broken for Gulp 3.7.0+

### ISSUE THREAD

**Issue by berezovskyi** [jiemakel/aether#3]
I was unable to figure out the solution, resorted to downgrading to 3.6.x. I was getting the following errors:

```
[03:12:26] gulp-notify: [Error running Gulp] TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:284:9)
    at Function.Buffer.from (buffer.js:116:10)
    at new Buffer (buffer.js:95:17)
    at DestroyableTransform.modifyLS [as _transform] (/Users/andrew/code/aether/node_modules/gulp-livescript/lib/index.js:37:25)
    at DestroyableTransform.Transform._read (/Users/andrew/code/aether/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/andrew/code/aether/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/andrew/code/aether/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/andrew/code/aether/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/andrew/code/aether/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at DestroyableTransform.ondata (/Users/andrew/code/aether/node_modules/gulp-sourcemaps/node_modules/readable-stream/lib/_stream_readable.js:531:20)
```

**Comment by berezovskyi** [comment]
on another project of yours, `fibra`, I was able to run the following without any errors:

```
yarn
gulp
gulp serve
```

CLI gulp is 3.9.1
