### ISSUE TITLE
'dist' task fails

### ISSUE THREAD

**Issue by berezovskyi** [jiemakel/aether#6]
```
./node_modules/.bin/gulp --require LiveScript dist
[04:22:26] Requiring external module LiveScript
[04:22:27] Using gulpfile ~/code/aether/gulpfile.ls
[04:22:27] Starting 'dist'...
[04:22:27] Starting 'build'...
[04:22:27] Starting 'clean'...
[04:22:27] Finished 'clean' after 71 ms
[04:22:27] Starting 'wiredep:styles'...
[04:22:27] Starting 'wiredep:scripts'...
[04:22:27] Starting 'templates'...
[04:22:27] Starting 'styles'...
[04:22:28] Starting 'scripts'...
[04:22:30] Finished 'styles' after 2.37 s
[04:22:30] Finished 'wiredep:styles' after 2.68 s
[04:22:30] Finished 'wiredep:scripts' after 2.66 s
[04:22:30] Starting 'wiredep'...
[04:22:30] Finished 'wiredep' after 33 μs
[04:22:30] Finished 'scripts' after 2.02 s
[04:22:30] Finished 'templates' after 2.66 s
[04:22:30] Finished 'build' after 2.76 s
[04:22:30] Starting 'dist:partials'...
[04:22:30] Starting 'dist:images'...
[04:22:30] Starting 'dist:fonts'...
(node:65096) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[04:22:30] gulp-size: total 0 B
[04:22:30] Finished 'dist:images' after 471 ms
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/gifsicle-bin/v0.1.7/vendor/osx/gifsicle',
  name: 'gifsicle',
  os: 'darwin' }
  at assertPath (path.js:7:11)
  at Object.basename (path.js:1355:5)
  at /Users/andrew/code/aether/node_modules/download/index.js:35:43
  at each (/Users/andrew/code/aether/node_modules/download/node_modules/each-async/each-async.js:63:4)
  at module.exports (/Users/andrew/code/aether/node_modules/download/index.js:33:5)
  at /Users/andrew/code/aether/node_modules/bin-wrapper/index.js:108:20
  at /Users/andrew/code/aether/node_modules/bin-wrapper/index.js:141:24
  at /Users/andrew/code/aether/node_modules/bin-check/index.js:30:20
  at /Users/andrew/code/aether/node_modules/executable/index.js:39:20
  at FSReqWrap.oncomplete (fs.js:111:15)
```

**Comment by berezovskyi** [comment]
using macOS 10.12, Node 7.0.0.

**Comment by jiemakel** [comment]
Doesn't work even on Node 6. As the dirtiest of fixes, I pinned the Node version to 5 which worked.

**Comment by berezovskyi** [comment]
Thank you for getting back to me promptly, Eetu!

Just installed 5.12.0 using NVM and it still doesn't work properly for me. Sorry for not being able to debug this error well and make a proper PR, I never worked with Livescript and rather new to Gulp. This is my output:

```
~/code/aether (master ✘)✭ ᐅ npm -v
3.8.6
~/code/aether (master ✘)✭ ᐅ node -v
v5.12.0
~/code/aether (master ✘)✭ ᐅ ./node_modules/.bin/gulp -v
[12:51:46] Requiring external module livescript
[12:51:46] CLI version 3.9.0
[12:51:46] Local version 3.9.0
~/code/aether (master ✘)✭ ᐅ ./node_modules/.bin/gulp serve
[12:51:51] Requiring external module livescript
[12:51:52] Using gulpfile ~/code/aether/gulpfile.ls
[12:51:52] Starting 'build'...
[12:51:52] Starting 'clean'...
[12:51:52] Finished 'clean' after 46 ms
[12:51:52] Starting 'wiredep:styles'...
[12:51:52] Starting 'wiredep:scripts'...
[12:51:52] Starting 'templates'...
[12:51:52] Starting 'styles'...
[12:51:52] Starting 'scripts'...
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'main' of undefined
    at findMainFiles (/Users/andrew/code/aether/node_modules/wiredep/lib/detect-dependencies.js:89:39)
    at /Users/andrew/code/aether/node_modules/wiredep/lib/detect-dependencies.js:151:17
    at forOwn (/Users/andrew/code/aether/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.forEach (/Users/andrew/code/aether/node_modules/lodash/dist/lodash.js:3303:9)
    at detectDependencies (/Users/andrew/code/aether/node_modules/wiredep/lib/detect-dependencies.js:33:7)
    at wiredep (/Users/andrew/code/aether/node_modules/wiredep/wiredep.js:65:39)
    at DestroyableTransform._transform (/Users/andrew/code/aether/node_modules/wiredep/wiredep.js:134:34)
    at DestroyableTransform.Transform._read (/Users/andrew/code/aether/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/andrew/code/aether/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/andrew/code/aether/node_modules/readable-stream/lib/_stream_writable.js:237:10)
~/code/aether (master ✘)✭ ᐅ git id
62bd1eb0
```

P.S. The dirty status of the repo is only due to the `.nvmrc` file, otherwise the branch is in sync with master.

**Comment by jiemakel** [comment]
You forgot to run `bower install` before trying to build.
